### ISSUE TITLE
The deployed example is not working

### ISSUE THREAD

**Issue by rabiibouhestine** [FrissAnalytics/shiny-vue-r#1]
Hi @FrissAnalytics, I have tried running the app locally as well, and it doe not work either, the browser console has the same errors as the deployed example provided here: https://friss.shinyapps.io/shiny-vue-r/

I am using Google Chrome Version 97.0.4692.99, R version 4.1.2

**Comment by FrissAnalytics** [comment]
Hi!

thanks for reporting it, I see the error as well. I guess some of the dependencies have changed, mostly likely related to Vue router:

![image](https://user-images.githubusercontent.com/11570078/154253365-1834244b-5f1c-4c2b-9f53-24d08e7582db.png)

I will take a look and fix it and let you know.

kind regards, Herman

**Comment by FrissAnalytics** [comment]
hi! I've just merged the PR, thanks for the help and the kind words!
