### ISSUE TITLE
blank (black) screen

### ISSUE THREAD

**Issue by kendavidn** [FrissAnalytics/shiny-vue-r#3]
Hello! Your work looks amazing! 

The sample (https://friss.shinyapps.io/shiny-vue-r/) does appear to be running at the moment. Shows a black screen and nothing else.

**Comment by FrissAnalytics** [comment]
hi! thanks for the kind words :-). There was a vue router dependency update that broke the app. A fix was pushed a few weeks ago but unfortunately I forgot to re-publish the app. It should work again, thanks for spotting this!
